# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Curt Clifton"
tagline: ""
description: "Follow <a href=\"https://micro.blog/curt\">@curt on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/curt\">@curt on Micro.blog</a>."
baseurl: ""
url: "http://microblog.curtclifton.net"
markdown: "kramdown"
username: "curt"
microblog_user: "curt"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Curt Clifton"
name: "Curt Clifton"
gravatar_hash: "446db4307ac0d39e08cd818906ad7af8"
avatar: "https://micro.blog/curt/avatar.jpg"
full_name: "Curt Clifton"
bio: ""
twitter_username: "curtclifton"
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "235"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Curt Clifton"